name: Rust test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: sudo apt -qq --no-install-recommends --yes install mingw-w64 && rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose